export enum AttributeSlugConfig {
  provisionAmount = "provisionAmount",
  payAmount = "payAmount",
  contingencyLevel = "contingencyLevel",
  criticalProcess = "criticalProcess",
  successRate = "successRate",
  resume = "resume",
  principalSituation = "principalSituation",
  resultProcess = "resultProcess",
  sede = "sede",
  startDate = "startDate",
  cause = "cause",
  comments = "comments",
  lawyerEmail = "lawyerEmail",
  principalLawyer = "principalLawyer",
  amount = "amount",
  connectLegal = "connectLegal",
  actualState = "actualState",
  risks = "risks",
  lastDate = "lastDate", //fecha de actualizacion
  lastSituation = "lastSituation", //ultimo actuado
  nextSituation = "nextSituation", // proxima acción
  numberCase = "numberCase", // número de caso
  stage = "stage", // etapa
  wronged = "wronged", // agraviado
  internalSpecialist = "internalSpecialist",
  commentsForResult = "commentsForResult",
  supervisionAmount = "supervisionAmount",
  supervisionProvisionContingency = "supervisionProvisionContingency",
  supervisionProvisionAmount = "supervisionProvisionAmount",
  supervisionPayAmount = "supervisionPayAmount",
  supervisionContingencyLevel = "supervisionContingencyLevel",
  supervisionCriticalProcess = "supervisionCriticalProcess",
  supervisionActualState = "supervisionActualState",
  supervisionSuccessRate = "supervisionSuccessRate",
  supervisionResume = "supervisionResume",
  supervisionPrincipalSituation = "supervisionPrincipalSituation",
  supervisionComments = "supervisionComments",
  supervisionSede = "supervisionSede",
  supervisionStartDate = "supervisionStartDate",
  supervisionCause = "supervisionCause",
  supervisionLawyerEmail = "supervisionLawyerEmail",
  supervisionLastDate = "supervisionLastDate", //fecha de actualizacion
  supervisionLastSituation = "supervisionLastSituation", //ultimo actuado
  supervisionNextSituation = "supervisionNextSituation", // proxima acción
  supervisionInternalSpecialist = "supervisionInternalSpecialist",
  supervisionCommentsForResult = "supervisionCommentsForResult",
  supervisionRisks = "supervisionRisks",
  supervisionConnectLegal = "supervisionConnectLegal",
  supervisionPrincipalLawyer = "supervisionPrincipalLawyer",
}
