export enum AttributeSlugConfig {
  provisionAmount = "provisionAmount",
  payAmount = "payAmount",
  contingencyLevel = "contingencyLevel",
  criticalProcess = "criticalProcess",
  actualState = "actualState",
  lastSituation = "lastSituation",
  successRate = "successRate",
  resume = "resume",
  principalSituation = "principalSituation",
  comments = "comments",
  amount = "amount",
  supervisionAmount = "supervisionAmount",
  supervisionProvisionContingency = "supervisionProvisionContingency",
  supervisionProvisionAmount = "supervisionProvisionAmount",
  supervisionPayAmount = "supervisionPayAmount",
  supervisionContingencyLevel = "supervisionContingencyLevel",
  supervisionCriticalProcess = "supervisionCriticalProcess",
  supervisionActualState = "supervisionActualState",
  supervisionLastSituation = "supervisionLastSituation",
  supervisionSuccessRate = "supervisionSuccessRate",
  supervisionResume = "supervisionResume",
  supervisionPrincipalSituation = "supervisionPrincipalSituation",
  supervisionComments = "supervisionComments",
}
