export enum AttributeSlugConfig {
  provisionAmount = "provisionAmount",
  payAmount = "payAmount",
  contingencyLevel = "contingencyLevel",
  criticalProcess = "criticalProcess",
  successRate = "successRate",
  resume = "resume",
  principalSituation = "principalSituation",
  sede = "sede",
  startDate = "startDate",
  cause = "cause",
  comments = "comments",
  lawyerEmail = "lawyerEmail",
  amount = "amount",
  actualState = "actualState",
  lastDate = "lastDate", //fecha de actualizacion
  lastSituation = "lastSituation", //ultimo actuado
  nextSituation = "nextSituation", // proxima acción
  supervisionAmount = "supervisionAmount",
  supervisionProvisionContingency = "supervisionProvisionContingency",
  supervisionProvisionAmount = "supervisionProvisionAmount",
  supervisionPayAmount = "supervisionPayAmount",
  supervisionContingencyLevel = "supervisionContingencyLevel",
  supervisionCriticalProcess = "supervisionCriticalProcess",
  supervisionActualState = "supervisionActualState",
  supervisionSuccessRate = "supervisionSuccessRate",
  supervisionResume = "supervisionResume",
  supervisionPrincipalSituation = "supervisionPrincipalSituation",
  supervisionComments = "supervisionComments",
  supervisionSede = "supervisionSede",
  supervisionStartDate = "supervisionStartDate",
  supervisionCause = "supervisionCause",
  supervisionLawyerEmail = "supervisionLawyerEmail",
  supervisionLastDate = "supervisionLastDate", //fecha de actualizacion
  supervisionLastSituation = "supervisionLastSituation", //ultimo actuado
  supervisionNextSituation = "supervisionNextSituation", // proxima acción
}
